# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-22 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20170822_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
