# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-22 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_tag_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='rank',
            field=models.FloatField(default=0),
        ),
    ]
