# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160513_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default='ok', max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
